language: node_js
node_js:
  - "8"
dist: trusty
sudo: required
services:
  - docker
script: "npm run test"
after_success:
  - npm run coverage
notifications:
  slack:
    secure: JGiQSTNio0cMRdGa5jg4dy7g7GrTEA0+RcYsZCV87AERH63LD81cf8J7dZB/PBpqtJi6fG0v+Ov6Vsy61SoO8V5dqxLhfEYqoRVI0GVfFBDHK3UvGoEJv32miTlURMKHbqEnBQ90jwOcnJo9s/g1s37Kl7N6UQl6QK9dGpeCLYql2wwwDWA0WVvwqN2Hsl3IiyaVePb3mypDnZVwVOocy6pmgp1oBzQs4q50AtCfB6bETt7i9F0qnX7d2rgiZor6BrISlwp0hLHOb4z90Xy8nLIXEOA7rv+lPiJs/euD1zO9gHCc5b3KXbVovuifcJBNC0OaTph8m2tPXI8gknPLSReK/3CGFp7QCV0nmIbBbLEj674VXHvFu9Pw5MxnaagyZD3DcsgwXJF3EEfuOKFctXOxMYR30YRUwL55TujtEkKWOY1cVMJ8oslGUEIzfkpNqikNNlnnw7YtLuJJkfcZsSTMeVPsPv8y8+feoYPgRY6dp84SwYilxAy5neWNIg21At2K4yHTQCdGutHxrFk10VeWom9zw/vXVmVzEipf8FjxeKv66NQS2hl5K72RouzsG/TtEFcPRxl8BB7jowBgdURPRAZ9xBWZ1wWwvPZGs8Sr3i/NPckIp+qrD6qoUQL/6MDgvtKoto8IDZJSoCIduxXFjZuAnaZ2JR9HOeDGM28=
